version: '3.8'

services:
  wordpress:
    build: ./requirements/wordpress/
    container_name: wp_container
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/mariadb/
    container_name: db_container
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app_network

  nginx:
    build: ./requirements/nginx/
    container_name: nginx_container
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - ./requirements/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "443:443"
    networks:
      - app_network
    depends_on:
      - wordpress

networks:
  app_network:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/Probook/data/wordpress
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/Probook/data/db_data