# image
FROM alpine:3.18

# installe mdb et client sans cache
RUN apk add --no-cache mariadb mariadb-client

# prep répertoires
RUN mkdir -p /var/run/mysqld && chown mysql:mysql /var/run/mysqld
RUN mkdir -p /docker-entrypoint-initdb.d

# conf mdb ac conf personnalisé
COPY config/conf.cnf /etc/my.cnf.d/conf.cnf
COPY config/conf.cnf /etc/my.cnf
RUN rm /etc/my.cnf.d/mariadb-server.cnf && mv /etc/my.cnf.d/conf.cnf /etc/my.cnf.d/mariadb-server.cnf

# Copie +run les scripts pour l'init de mdb
COPY scripts/entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh
COPY scripts/setup.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/setup.sh

EXPOSE 3306

# point d'entrée pour init mdb au démarrage du conteneur
ENTRYPOINT ["/entrypoint.sh"]
