FROM alpine:3.18

RUN apk add --no-cache php81 php81-fpm php81-mysqli php81-json php81-openssl \
    php81-curl php81-zlib php81-xml php81-phar php81-intl php81-dom php81-xmlreader \
    php81-ctype php81-mbstring php81-gd curl

RUN addgroup -S www-data || true && adduser -S -G www-data www-data || true

WORKDIR /var/www/html

RUN curl -O https://wordpress.org/latest.tar.gz \
	&& tar -xzf latest.tar.gz --strip-component=1 \
	&& rm latest.tar.gz \
	&& chown -R nobody:nobody /var/www/html

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

COPY config/php-fpm.conf /etc/php81/php-fpm.d/www.conf
COPY config/inception.xml /usr/local/bin/inception.xml
COPY scripts/docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 9000

VOLUME /var/www/html

ENTRYPOINT ["docker-entrypoint.sh"]
