#!/bin/bash
cat << EOF > /tmp/db_config.sql
CREATE DATABASE IF NOT EXISTS $MYSQL_DB; 
CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASS';
GRANT ALL PRIVILEGES ON $MYSQL_DB.* TO '$MYSQL_USER'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASS';
FLUSH PRIVILEGES;
EOF
mysql -h localhost < /tmp/db_config.sql