FROM alpine:3.18

# Install necessary packages
RUN apk update && apk upgrade && apk add openssl nginx curl vim sudo

# Create necessary directories
RUN mkdir -p /run/nginx

# Copy configuration and setup scripts
COPY ./config/nginx.conf /etc/nginx/nginx.conf
COPY ./scripts/setup_nginx.sh /setup_nginx.sh

# Generate SSL certificates
RUN mkdir -p /etc/nginx/ssl && \
    openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
    -out /etc/nginx/ssl/certificate.crt \
    -keyout /etc/nginx/ssl/private.key \
    -subj "/CN=nmuminov.42.fr"

# Make setup script executable
RUN chmod +x /setup_nginx.sh

# Expose HTTPS port
EXPOSE 443

# Set entrypoint
ENTRYPOINT ["sh", "setup_nginx.sh"]
